# Generated by Django 2.2.6 on 2020-04-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='address',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='city',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='gen',
        ),
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
