# Generated by Django 2.2.6 on 2020-04-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin', '0003_booking_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='res_time',
            new_name='time',
        ),
        migrations.AddField(
            model_name='booking',
            name='book_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='order_date',
            field=models.DateField(null=True),
        ),
    ]
