# Generated by Django 2.2.6 on 2020-04-26 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin', '0004_auto_20200427_0223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Send_Feedback',
        ),
    ]
